config/routes.rb
ClabDb::Application.routes.draw do
  

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :oligos, only: [:new, :create, :update, :destroy]
  resources :plasmids, only: [:new, :create, :update, :destroy]
  resources :seeds, only: [:new, :create, :update, :destroy]
  

  
  root  'pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'pages#help',    via: 'get'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/plasmids',  to: 'pages#plasmids',    via: 'get'
  match '/seeds', to: 'pages#seeds', via: 'get'
  match '/oligos', to: 'pages#oligos', via: 'get'
  
  resources :plasmids do
    get 'download', on: :member
  end
  
  

end

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  <a>Update details here</a>
</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<p>
  <a>Update details here</a>
</p>

app/views/pages/home.html.erb
<body>
  <div class="center jumbotron" class="bckimg">
    <h1>Lab Database</h1>
    <h2>
      Plasmids . Seeds . Oligos
    </h2>
    <%= link_to "Oligo Database", oligos_path, class: "btn btn-sm" %><br><br>
    <%= link_to "Seed Database", seeds_path, class: "btn btn-sm" %><br><br>
    <%= link_to "Plasmid Database", plasmids_path, class: "btn btn-sm" %><br><br><br><br><br>
    <%= link_to "Sign Up", signup_path, class: "btn btn-sm" %>
  </div>


</body>    
   
 

app/views/pages/oligos.html.erb
<% provide(:title, 'Oligos') %>
<h3>Oligo Database</h3>

<br>
<br>
   <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="oligos">
    <thead>                         
      <tr>
        <th>Oligo no.</th>                          
        <th>Name</th>
        <th>Sequence</th>
        <th>Tm (&deg;C)</th>
        <th>Description</th>
        <th>Designer</th>
        <th>Delete?</th>

        
      </tr>
    </thead>
    <tbody>
      <% @oligos.each do |oligos| %>       
      <tr>
        <td><%= oligos.oligo_no  %></td>
        <td><%= best_in_place oligos, :name %></td>
        <td><%= best_in_place oligos, :sequence   %></td>
        <td><%= best_in_place oligos, :tm  %></td>
        <td><%= best_in_place oligos, :descrip   %></td>
        <td><%= best_in_place oligos, :designer  %></td>
        <td><%= link_to "Delete", oligos, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-sm"%></td>    
      </tr>
    <% end %>
  </tbody>
</table> 
<br>
<%= render 'shared/oligo_form' %>

app/views/pages/plasmids.html.erb
<% provide(:title, 'Plasmids') %>
<h3>Plasmid Database</h3>

<br>
<br>
<h5>Show only ligation numbers between:</h5>
  <div id ="lig"></div><br>

   <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="plasmids">
    <thead>                         
      <tr>
        <th>Ligation no.</th>                          
        <th>Vector backbone</th>
        <th>Insert</th>
        <th>pUQC no.</th>
        <th>Description</th>
        <th>Designer</th>
        <th>Operations</th>

        
      </tr>
    </thead>
    <tbody>
      <% @plasmids.each do |plasmids| %>       
      <tr>
        <td><%= plasmids.ligation  %></td>
        <td><%= best_in_place plasmids, :vec_backbone  %></td>
        <td><%= best_in_place plasmids, :insert %></td>
        <td><%= best_in_place plasmids, :puqc %></td>
        <td><%= best_in_place plasmids, :descrip  %></td>
        <td><%= best_in_place plasmids, :designer  %></td>
        <td><%= link_to "Delete", plasmids, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-sm"%>
        <%= link_to 'Get GBK', download_plasmid_path(plasmids.id), class: "btn btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table> 
<br>
<%= render 'shared/plasmid_form' %>

app/views/pages/seeds.html.erb
<% provide(:title, 'Seeds') %>
<h3>Seed Database</h3>

<br>
<br>
   <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="seeds">
    <thead>                         
      <tr>
        <th>Tube no.</th>                          
        <th>Collection Date</th>
        <th>Parental Tube No.</th>
        <th>Genotype</th>
        <th>Description</th>
        <th>Sourced By</th>
        <th>GMO?</th>
        <th>Delete?</th>

        
      </tr>
    </thead>
    <tbody>
      <% @seeds.each do |seeds| %>       
      <tr>
        <td><%= seeds.tube_no  %></td>
        <td><%= best_in_place seeds, :seed_col_date %></td>
        <td><%= best_in_place seeds, :par_tube  %></td>
        <td><%= best_in_place seeds, :genotype %></td>
        <td><%= best_in_place seeds, :descrip  %></td>
        <td><%= best_in_place seeds, :sourced_by  %></td>
        <td><%= best_in_place seeds, :GMO %></td>
        <td><%= link_to "Delete", seeds, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-sm"%></td>

        
      </tr>
    <% end %>
  </tbody>
</table> 
<br>
<%= render 'shared/seed_form' %>

app/views/pages/signup.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>
<p>
  SocGen
</p>